'use client';
import {useState} from 'react';
import s from './AdminRequestsCards.module.css';
export type AdminRequest={id:string;request_id:string;kind:'TOPUP'|'CRYPTO'|'BANK'|'CASHOUT';username:string;amount:number;charge:number;final_amount:number;status:string;created_at:string;token_no?:string|null;city?:string|null;area?:string|null;area_code?:string|null;payment_address?:string|null;offered_address?:string|null;destination_wallet?:string|null;crypto_symbol?:string|null;crypto_network?:string|null;bank_holder?:string|null;bank_name?:string|null;bank_account?:string|null;bank_ifsc?:string|null;bank_account_type?:string|null};
const money=(n:number)=>Number(n||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
function Field({label,value,wide=false}:{label:string;value:any;wide?:boolean}){return <div className={wide?s.wide:''}><div className={s.label}>{label}</div><div className={s.fieldValue}>{value||'—'}</div></div>}
export function AdminRequestsCards({rows,call}:{rows:AdminRequest[];call:any}){const[cash,setCash]=useState<AdminRequest|null>(null),[address,setAddress]=useState(''),[err,setErr]=useState('');const words=address.trim()?address.trim().split(/\s+/).length:0;
 const act=(r:AdminRequest,action:string)=>{if(r.kind==='CASHOUT'&&action==='COMPLETE'){setCash(r);setAddress('');setErr('');return}const note=window.prompt(action==='COMPLETE'?(r.kind==='TOPUP'?'Verify payment / comment':r.kind==='CRYPTO'?'Transaction hash / comment':'Bank reference / comment'):'Comment / reason','')||'';return call('/api/admin/request-action',{kind:r.kind,request_id:r.id,action,note})};
 async function confirm(){if(!cash)return;if(!address.trim()){setErr('Please enter the cash collection / payment address.');return}if(words>100){setErr('Maximum 100 words.');return}const saved=await call('/api/admin/cashout-offer',{request_id:cash.id,city:cash.city||'',area:cash.area||'',area_code:cash.area_code||'',address:address.trim(),note:'Cash collection address confirmed'},false);if(!saved)return;const done=await call('/api/admin/cashout-action',{request_id:cash.id,action:'COMPLETE',note:'Cash paid; token revealed to user'});if(done)setCash(null)}
 return <><div className={s.toolbar}><div><h2>Transaction requests</h2><p>Complete request details, destination information and processing status.</p></div><div className={s.count}>{rows.length} requests</div></div><div className={s.list}>{rows.map(r=>{const closed=['completed','rejected','cancelled'].includes(r.status);return <article className={s.card} key={r.kind+r.id}><header className={s.head}><div className={s.identity}><span className={`${s.type} ${s[r.kind.toLowerCase()]}`}>{r.kind==='CASHOUT'?'CASH OUT':r.kind}</span><div><div className={s.requestId}>{(r.kind==='TOPUP'||r.kind==='CASHOUT')&&r.token_no?r.token_no:r.request_id}</div>{r.token_no&&<div className={s.subId}>{r.request_id}</div>}</div></div><div className={`${s.status} ${s['status_'+r.status]}`}>{r.status}</div></header>
 <div className={s.summary}><Field label="User" value={'@'+r.username}/><Field label="Requested amount" value={`${money(r.amount)} VC`}/><Field label="Charge" value={`${money(r.charge)} VC`}/><Field label="Final / Total" value={`${money(r.final_amount)}${r.kind==='CRYPTO'&&r.crypto_symbol?' '+r.crypto_symbol:' VC'}`}/><Field label="Date & time" value={new Date(r.created_at).toLocaleString('en-IN')}/></div>
 {r.kind==='BANK'&&<section className={s.details}><div className={s.detailsTitle}>Bank destination details</div><div className={s.detailGrid}><Field label="Account holder" value={r.bank_holder}/><Field label="Bank name" value={r.bank_name}/><Field label="Account number" value={r.bank_account}/><Field label="IFSC" value={r.bank_ifsc}/><Field label="Account type" value={r.bank_account_type}/></div></section>}
 {r.kind==='CRYPTO'&&<section className={s.details}><div className={s.detailsTitle}>Crypto destination details</div><div className={s.detailGrid}><Field label="Asset" value={r.crypto_symbol}/><Field label="Network" value={r.crypto_network}/><Field label="Destination wallet" value={r.destination_wallet} wide/></div></section>}
 {(r.kind==='TOPUP'||r.kind==='CASHOUT')&&<section className={s.details}><div className={s.detailsTitle}>{r.kind==='TOPUP'?'Top-up payment location':'Cash collection / payment location'}</div><div className={s.detailGrid}><Field label="City" value={r.city}/><Field label="Area" value={r.area}/><Field label="Area code" value={r.area_code}/><Field label="Address" value={r.kind==='CASHOUT'?(r.offered_address||r.payment_address):r.payment_address} wide/></div></section>}
 {!closed&&<footer className={s.actions}>{r.kind!=='CASHOUT'&&<button className={s.approve} onClick={()=>act(r,'APPROVED')}>Approve</button>}<button className={s.complete} onClick={()=>act(r,'COMPLETE')}>{r.kind==='TOPUP'?'Verify payment':r.kind==='CASHOUT'?'Cash paid':'Complete'}</button><button className={s.reject} onClick={()=>act(r,'REJECTED')}>Reject</button></footer>}</article>})}</div>
 {cash&&<div className={s.overlay} onClick={()=>setCash(null)}><div className={s.modal} onClick={e=>e.stopPropagation()}><h2>Cash paid confirmation</h2><p>@{cash.username} · {money(cash.amount)} VC</p><div className={s.modalLocation}>{cash.city||'—'} / {cash.area||'—'} · {cash.area_code||'—'}</div><textarea rows={5} placeholder="Cash collection / payment address (maximum 100 words)" value={address} onChange={e=>{const v=e.target.value;const n=v.trim()?v.trim().split(/\s+/).length:0;if(n<=100){setAddress(v);setErr('')}}}/><div className={s.wordCount}>{words}/100 words</div>{err&&<div className={s.error}>{err}</div>}<div className={s.actions}><button className={s.complete} onClick={confirm}>Cash paid — complete</button><button className={s.cancel} onClick={()=>setCash(null)}>Cancel</button></div></div></div>}</>}
