'use client';
import { useMemo, useState } from 'react';
import s from './AdminDesktopPanel.module.css';

type User={id:string;username:string;full_name:string|null;email:string|null;role:string;status:string;master_id:string|null;balance:number;address:string|null;wallet_status:string};
type Req={id:string;request_id:string;kind:string;username:string;amount:number;status:string};
type Ledger={id:string;transaction_type:string;amount:number;balance_before:number;balance_after:number;created_at:string;profiles?:{username?:string}|null};
const sections=['Overview','Masters','Users','Wallet ledger','Requests','Charges','Commissions','Permissions','Audit log'];
export function AdminDesktopPanel({signedInAs,users,requests,ledger,totalCommission,adminWallet}:{signedInAs:string;users:User[];requests:Req[];ledger:Ledger[];totalCommission:number;adminWallet:number}){
 const [tab,setTab]=useState('Overview'),[selected,setSelected]=useState(users.find(u=>u.role==='user')?.username||''),[amount,setAmount]=useState(''),[msg,setMsg]=useState('');
 const masters=useMemo(()=>users.filter(u=>u.role==='master'),[users]); const normals=useMemo(()=>users.filter(u=>u.role==='user'),[users]);
 async function call(url:string,body:any){setMsg('Working…');try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw new Error(d.error||'Request failed');setMsg('Done');setTimeout(()=>location.reload(),450)}catch(e:any){setMsg(e.message||'Failed')}}
 function exportData(){const blob=new Blob([JSON.stringify({users,requests,ledger},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vcoin-admin-export.json';a.click();URL.revokeObjectURL(a.href)}
 return <div className={s.shell}><aside className={s.side}><div className={s.brand}><div className={s.logo}>V</div><div><div className={s.brandTitle}>V Coin</div><div className={s.muted}>Admin panel</div></div></div><nav className={s.nav}>{sections.map(x=><button key={x} onClick={()=>setTab(x)} className={`${s.navBtn} ${tab===x?s.active:''}`}>{x}</button>)}</nav><div className={s.sideBottom}><button className={s.outline} onClick={exportData}>Export data (.json)</button><button className={s.outline} onClick={()=>location.href='/dashboard'}>Open user wallet</button><button className={s.outline} onClick={()=>location.reload()}>Refresh data</button></div></aside><main className={s.main}><div className={s.top}><div><div className={s.mobileTop}>V Coin · Admin</div><h1 className={s.title}>{tab}</h1><div className={s.sub}>Live snapshot of the platform · Signed in as @{signedInAs}</div></div><div className={s.who}>@{signedInAs} · Admin</div></div>{tab==='Overview'&&<><div className={s.cards}><K label="Wallet balance" value={`${adminWallet.toFixed(2)} VC`}/><K label="Active users" value={String(users.filter(u=>u.status==='active').length)}/><K label="Total commission" value={`${totalCommission.toFixed(2)} VC`}/><K label="Masters" value={String(masters.length)}/><K label="Pending requests" value={String(requests.filter(r=>r.status==='pending').length)}/></div><div className={s.grid2}><div><section className={s.panel}><h2 className={s.panelTitle}>Transactions (Last 7 days)</h2><div className={s.chart}><div className={s.line}/></div></section><section className={s.panel}><div className={s.sectionHead}><h2 className={s.panelTitle}>Recent activity</h2><button className={s.dark} onClick={()=>setTab('Wallet ledger')}>View all</button></div><LedgerTable rows={ledger.slice(0,8)}/></section></div><div><section className={s.panel}><h2 className={s.panelTitle}>Quick actions</h2><div className={s.actions}><button className={s.gold} onClick={()=>setTab('Users')}>+ Manage users</button><button className={s.dark} onClick={()=>setTab('Masters')}>+ Masters</button><button className={s.green} onClick={()=>setTab('Users')}>Credit VC</button><button className={s.red} onClick={()=>setTab('Users')}>Debit VC</button><button className={s.dark} onClick={()=>setTab('Requests')}>Approve requests</button><button className={s.dark} onClick={()=>setTab('Wallet ledger')}>View ledger</button></div></section><section className={s.panel}><h2 className={s.panelTitle}>System status</h2><div style={{color:'#61d6a5'}}>● Supabase connected</div><div className={s.muted} style={{marginTop:7}}>Data loaded from production tables</div></section></div></div></>}
 {tab==='Users'&&<><section className={s.panel}><h2 className={s.panelTitle}>Admin VC credit / debit</h2><div className={s.form}><select className={s.input} value={selected} onChange={e=>setSelected(e.target.value)}>{normals.map(u=><option key={u.id} value={u.username}>@{u.username} — {u.full_name||u.username}</option>)}</select><input className={s.input} type="number" min="0.01" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><button className={s.gold} onClick={()=>call('/api/admin/credit',{username:selected,amount:Number(amount),idempotencyKey:crypto.randomUUID()})}>Credit VC</button><button className={s.red} onClick={()=>call('/api/admin/debit',{username:selected,amount:Number(amount),idempotencyKey:crypto.randomUUID()})}>Debit VC</button></div>{msg&&<div className={s.message}>{msg}</div>}</section><UsersTable rows={normals}/></>}
 {tab==='Masters'&&<UsersTable rows={masters}/>} {tab==='Wallet ledger'&&<section className={s.panel}><h2 className={s.panelTitle}>Wallet ledger</h2><LedgerTable rows={ledger}/></section>} {tab==='Requests'&&<section className={s.panel}><h2 className={s.panelTitle}>Requests</h2><div className={s.tableWrap}><table className={s.table}><thead><tr><th>ID</th><th>Type</th><th>User</th><th>Amount</th><th>Status</th></tr></thead><tbody>{requests.map(r=><tr key={r.kind+r.id}><td>{r.request_id}</td><td>{r.kind}</td><td>@{r.username}</td><td>{r.amount.toFixed(2)} VC</td><td><span className={s.badge}>{r.status}</span></td></tr>)}</tbody></table></div></section>} {['Charges','Commissions','Permissions','Audit log'].includes(tab)&&<section className={s.panel}><h2 className={s.panelTitle}>{tab}</h2><div className={s.empty}>This desktop section is ready for your existing backend controls. No user-side files were changed.</div></section>}</main></div>
}
function K({label,value}:{label:string;value:string}){return <div className={s.card}><div className={s.label}>{label}</div><div className={s.value}>{value}</div></div>}
function UsersTable({rows}:{rows:User[]}){return <section className={s.panel}><div className={s.tableWrap}><table className={s.table}><thead><tr><th>User</th><th>Email</th><th>Status</th><th>Wallet</th><th>Balance</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><b>@{u.username}</b><br/><span className={s.muted}>{u.full_name}</span></td><td>{u.email||'—'}</td><td><span className={s.badge}>{u.status}</span></td><td>{u.wallet_status}</td><td>{u.balance.toFixed(2)} VC</td></tr>)}</tbody></table></div></section>}
function LedgerTable({rows}:{rows:Ledger[]}){return <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Type</th><th>User</th><th>Amount</th><th>Before</th><th>After</th><th>Date</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.id}><td>{r.transaction_type}</td><td>@{r.profiles?.username||'user'}</td><td>{Number(r.amount||0).toFixed(2)}</td><td>{Number(r.balance_before||0).toFixed(2)}</td><td>{Number(r.balance_after||0).toFixed(2)}</td><td>{new Date(r.created_at).toLocaleString()}</td></tr>):<tr><td colSpan={6} className={s.empty}>No transactions yet.</td></tr>}</tbody></table></div>}
