'use client';
import { useEffect,useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { TxRow } from '@/components/ui';

type Row={id:string;transaction_id?:string;transaction_type?:string;direction:string;amount:number;created_at:string;description?:string;reference_id?:string};
type Detail={transactionId:string;username:string;fee:number;amount:number;direction:'sent'|'received';createdAt:string};

function usernameFrom(row:Row){
 const m=(row.description||'').match(/(?:to|from)\s+@([^\s]+)/i);
 return m?.[1]||'user';
}
function baseTxn(row:Row){return row.reference_id||row.transaction_id?.replace(/-(?:D|C)$/,'')||row.transaction_id||row.id}

export function LiveRecentActivity({userId,initialRows}:{userId:string;initialRows:Row[]}){
 const [rows,setRows]=useState(initialRows),[selected,setSelected]=useState<Detail|null>(null);
 useEffect(()=>{const s=createClient();async function refresh(){const {data}=await s.from('wallet_transactions').select('id,transaction_id,transaction_type,direction,amount,created_at,description,reference_id').order('created_at',{ascending:false}).limit(3);if(data)setRows(data.map((x:any)=>({...x,amount:Number(x.amount)})))}const c=s.channel(`activity-${userId}`).on('postgres_changes',{event:'*',schema:'public',table:'wallet_transactions'},refresh).subscribe();return()=>{s.removeChannel(c)}},[userId]);
 async function open(row:Row){const direction=row.direction==='CREDIT'?'received':'sent';let fee=0,username=usernameFrom(row),amount=Number(row.amount),transactionId=baseTxn(row);const s=createClient();if(transactionId.startsWith('VCT-')){const {data}=await s.from('vcoin_transfers').select('transaction_id,amount,charge,sender_user_id,receiver_user_id').eq('transaction_id',transactionId).maybeSingle();if(data){transactionId=data.transaction_id;amount=Number(data.amount);fee=Number(data.charge||0);const otherId=direction==='received'?data.sender_user_id:data.receiver_user_id;const {data:p}=await s.from('profiles').select('username').eq('id',otherId).maybeSingle();if(p?.username)username=p.username}}setSelected({transactionId,username,fee,amount,direction,createdAt:row.created_at})}
 if(!rows.length)return <p className="py-4 text-center text-[13px] text-muted-2">No transactions yet.</p>;
 return <>{rows.map(t=>{const received=t.direction==='CREDIT',username=usernameFrom(t);return <button type="button" key={t.id} onClick={()=>open(t)} className="block w-full text-left"><TxRow direction={received?'received':'sent'} name={received?'Received':'Sent'} subtitle={`${received?'From':'To'} @${username}`} time={new Date(t.created_at).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} amount={`${received?'+':'-'}${Number(t.amount).toFixed(2)} VC`}/></button>})}{selected&&<Receipt detail={selected} close={()=>setSelected(null)}/>}</>
}
function Receipt({detail,close}:{detail:Detail;close:()=>void}){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/60 sm:items-center sm:p-5" onClick={close}><div onClick={e=>e.stopPropagation()} className="w-full max-w-[470px] rounded-t-[28px] border border-line bg-panel2 px-6 pb-8 pt-5 shadow-2xl sm:rounded-[28px]"><div className="flex items-center justify-between"><button className="text-xl text-muted" onClick={()=>navigator.clipboard?.writeText(`Txn No: ${detail.transactionId}\n${detail.amount.toFixed(2)} VC`)}>↥</button><h2 className="font-display text-[22px] font-bold">{detail.direction==='received'?'Received':'Sent'}</h2><button onClick={close} className="text-[30px] leading-none">×</button></div><div className="py-9 text-center"><div className={`font-display text-[38px] font-extrabold ${detail.direction==='received'?'text-green':'text-cream'}`}>{detail.direction==='received'?'+':'-'}{detail.amount.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})} VC</div><div className="mt-2 text-[14px] text-muted">{detail.direction==='received'?`From @${detail.username}`:`To @${detail.username}`}</div></div><div className="space-y-5 text-[14px]"><Line label="Date" value={new Date(detail.createdAt).toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'})}/><Line label="Status" value="Completed" green/><Line label={detail.direction==='received'?'From':'To'} value={`@${detail.username}`}/><Line label="Txn No" value={detail.transactionId}/><Line label="Wallet Fees" value={`${detail.fee.toFixed(2)} VC`}/></div></div></div>}
function Line({label,value,green=false}:{label:string;value:string;green?:boolean}){return <div className="grid grid-cols-[105px_1fr] gap-3"><div className="text-muted">{label}</div><div className={`break-all text-right font-semibold ${green?'text-green':''}`}>{value}</div></div>}
