import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { AssetRow, IconChip } from '@/components/ui';
import { BottomNav } from '@/components/BottomNav';
import { RequestActivity, RequestActivityRow } from '@/components/RequestActivity';
export const dynamic='force-dynamic';export const revalidate=0;
export default async function AssetsPage(){const {supabase,profile}=await requireUser();const [{data:wallet},{data:topups},{data:crypto},{data:banks}]=await Promise.all([
supabase.from('wallets').select('vcoin_balance,locked_balance,status').eq('user_id',profile.id).single(),
supabase.from('topup_requests').select('id,request_id,requested_vcoin,topup_charge,status,created_at').eq('user_id',profile.id).order('created_at',{ascending:false}).limit(20),
supabase.from('crypto_conversion_requests').select('id,request_id,vcoin_amount,conversion_charge,network_charge,status,created_at,destination_wallet,final_crypto_amount').eq('user_id',profile.id).order('created_at',{ascending:false}).limit(20),
supabase.from('bank_transfer_requests').select('id,request_id,vcoin_amount,transfer_charge,status,created_at,final_bank_amount').eq('user_id',profile.id).order('created_at',{ascending:false}).limit(20)]);
const total=Number(wallet?.vcoin_balance||0),locked=Number(wallet?.locked_balance||0),available=total-locked;const fmt=(n:number)=>n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const requests:RequestActivityRow[]=[...(topups||[]).map((x:any)=>({id:x.id,kind:'TOPUP' as const,request_id:x.request_id,amount:Number(x.requested_vcoin),charge:Number(x.topup_charge||0),status:x.status,created_at:x.created_at})),...(crypto||[]).map((x:any)=>({id:x.id,kind:'CRYPTO' as const,request_id:x.request_id,amount:Number(x.vcoin_amount),charge:Number(x.conversion_charge||0)+Number(x.network_charge||0),status:x.status,created_at:x.created_at,detail:x.destination_wallet,final_value:x.final_crypto_amount?String(x.final_crypto_amount):undefined})),...(banks||[]).map((x:any)=>({id:x.id,kind:'BANK' as const,request_id:x.request_id,amount:Number(x.vcoin_amount),charge:Number(x.transfer_charge||0),status:x.status,created_at:x.created_at,final_value:x.final_bank_amount?String(x.final_bank_amount):undefined}))];requests.sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at));
return <div className="flex flex-1 flex-col overflow-hidden"><div className="flex-1 overflow-y-auto px-5 pb-6 pt-2"><div className="mb-5 flex items-center justify-between"><h1 className="font-display text-[19px] font-bold">Your assets</h1><IconChip name="bell" size={34} radius={17} color="text-cream"/></div><div className="mb-5"><div className="text-[12.5px] text-muted">Available V Coin</div><div className="mt-1 font-display text-[28px] font-extrabold tabular-nums">V {fmt(available)}</div>{locked>0&&<div className="mt-1 text-[12px] text-muted-2">Reserved V {fmt(locked)}</div>}</div><AssetRow mono="V" name="V Coin" holding={`V ${fmt(total)}`} value={`V ${fmt(available)}`} change={wallet?.status==='active'?'Active':'Frozen'} changeColor={wallet?.status==='active'?'text-green':'text-red'}/><div className="mt-6 grid grid-cols-2 gap-3"><Tile href="/topup" title="Top up" sub="Request more VC"/><Tile href="/crypto" title="Crypto" sub="Conversion request"/><Tile href="/bank" title="Bank transfer" sub="Convert VC to bank"/><Tile href="/history" title="History" sub="Wallet ledger"/></div><RequestActivity userId={profile.id} initialRows={requests.slice(0,20)}/></div><BottomNav/></div>}
function Tile({href,title,sub}:{href:string;title:string;sub:string}){return <Link href={href} className="rounded-2xl border border-line bg-panel2 p-4"><div className="text-[14px] font-semibold text-cream">{title}</div><div className="mt-1 text-[11.5px] text-muted-2">{sub}</div></Link>}
